{% set name = "onnxconverter-common" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/microsoft/{{ name }}
  git_rev: v{{ version }}
  patches:
    - 0001-Update-protobuf-pin-in-dist-info.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}
    - packaging

test:
  imports:
    - onnxconverter_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxconverter-common
  summary: Common utilities for ONNX converters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
