{% set name = "onnxconverter-common" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 32315bcc844a8203092f3117a4a092ac6cf03d6a20145477e284f1172557d6f9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}

test:
  imports:
    - onnxconverter_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxconverter-common
  summary: Common utilities for ONNX converters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
