{% set name = "onnxconverter-common" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f95f2a2d1fedc20cccbc820d4f63cbe84e287a5bd8c863ced400ae73946e13e6

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  string: pyh{{ PKG_HASH }}_pb{{ protobuf | replace(".*", "")}}_{{ PKG_BUILDNUM }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy {{ numpy }}
    - protobuf {{ protobuf }}
    - onnx {{ onnx }}

test:
  imports:
    - onnxconverter_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxconverter-common
  summary: Common utilities for ONNX converters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
